### ISSUE TITLE
Verification certificate should be cached

### ISSUE THREAD

**Issue by wstrange** [dbilgin/firebase_auth_admin_verify#1]
[Handy example - thanks for putting this together!]

The certificate looks like it is fetched every time a token is authenticated:
```
  final certificate = await _getCertificateByKid(kid);

```

That's going to be quite expensive, and probably not needed. Caching it would be useful.

**Comment by dbilgin** [comment]
Hi @wstrange! Thanks a lot for the suggestion, that makes sense, but one problem here is the certificates under `https://www.googleapis.com/robot/v1/metadata/x509/securetoken@system.gserviceaccount.com` actually change every couple of minutes, so they need to be reverified I think. Did you have something in your mind about caching?

**Comment by wstrange** [comment]
They might rotate them, but I think the issuer remains valid for quite some time (not sure what that limit is - still trying to find the definitive source on that..)

I can't imagine they would expect you to make an HTTP call to their endpoint on every single call to your service. 

I think you might want to consider deprecating this library with a note for folks to look at https://pub.dev/packages/openid_client 

I'd forgotten all about this library, but when I googled it, I came across a blog that I wrote (🤦 )
https://warrenstrange.medium.com/firebase-authentication-with-a-custom-dart-server-application-25037e2c6a2a

It's a fairly comprehensive library.  I basically replaced the `verifyFirebaseToken` call with this:

```dart
Future<OpenIdClaims> verifyFirebaseToken(String token) async {
  var c = oidcClient.createCredential(idToken: token);
  print(c.idToken.claims);

  var violations = c.validateToken(validateClaims: true, validateExpiry: true);

  await for (var v in violations) {
    // todo: throw some exception, etc.
    print('Violation $v');
  }

  return c.idToken.claims;
}
```

The oidc client is initialized one time only at server start:
```
  var issuer = await Issuer.discover(Issuer.firebase(firebaseId));
  oidcClient = Client(issuer,firebaseId);
```

It seems to be working fine with that "cached" issuer (30 minutes and counting..)

HTH

**Comment by dbilgin** [comment]
I'll have a look at it when I have some free time and deprecate it if that's the case, thanks for bringing this up

**Comment by wstrange** [comment]
This has some more info on key rotation: https://stackoverflow.com/questions/67122035/when-does-jwk-expire-jwks-rotation-policy 

From my experiment, it looks like the firebase key is still going strong after 30 minutes ;-)  

It might be prudent to have a Timer task that fetches the issuer every 60 minutes or so.  But for sure, I don't think you want to fetch it on every request,

**Comment by wstrange** [comment]
Just to satisfy my own curiosity here:  The cache control header on the certificate response is how long you can cache the cert for. 

You should fetch the JWK cert again before the expiry. For the Google JWK, it is approx. 6.5 hours.

**Comment by dbilgin** [comment]
Did as you suggested and discontinued the package, thank you for looking into this @wstrange
